### ISSUE TITLE
Passing of secrets not in line with best practice

### ISSUE THREAD

**Issue by ineffyble** [hashicorp/vault-lambda-extension#13]
This extension only allows the user to write the secrets to a file in the filesystem (e.g. `/tmp/...`) as a way to pass secrets to the Lambda function that needs them.

This is against [AWS best practice](https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html), which states "_don’t use the execution environment to store user data, events, or other information with security implications_".

Looking at the Lambda Extensions API, it should be possible for the Vault extension to set an environment variable instead, which can be read by the Lambda process.

**Comment by tomhjp** [comment]
Hi, thanks for opening this!

You're absolutely right that it's not best practice, and it's one of the things we wanted to get feedback on during the public preview period. Unfortunately, because this is an external extension which runs as its own process next to the function (as opposed to an internal extension), I don't think we can set environment variables for the main function process.

What we could do though is create a server mode that listens on a local socket with some API for requesting secrets. Then the extension wouldn't do much at startup, and instead respond to requests during execution time, passing secrets to the function through a TCP or unix socket. This is something we've discussed adding to the extension, but we don't have a firm design or timeframe yet - would it solve your concern? It's obviously a little more complex to use as a consumer, but hopefully that trade-off would be worth it to lots of users. On that note, I would love to understand more about your use case and how this problem impacts you if you're happy to share! 🙂

**Comment by ineffyble** [comment]
@tomhjp That sounds great - would certainly address my concern.

My context is working in a financial services environment with strict security requirements and controls. We're just starting to migrate to Hashicorp Vault for secrets management, and the extension seemed like a great way to accomplish this for Serverless microservices.

**Comment by AndreZiviani** [comment]
Hi @tomhjp 

I have a different use case that would benefit from this as well, I would like to dynamically access a Vault secret based on a parameter from the request, this TCP/socket interface would simplify my lambda a lot!

**Comment by dmattia** [comment]
+1 for the server idea. In ECS/EKS/EC2s where we use Vault in AWS, we can use the `vault agent`. I would love it if this extension worked similarly, allowing us to communicate with it just like the agent endpoint.

**Comment by tomhjp** [comment]
Proxy server mode released in layer version 8/git tag v0.3.0 🎉 

Check out the demo function in `quick-start` for a concrete example of consuming the proxy from Lambda, and please feel free to raise further issues with feedback! Thanks all for your input.
