### ISSUE TITLE
vault lambda extension not working

### ISSUE THREAD

**Issue by rudub** [hashicorp/vault-lambda-extension#36]
Hi all,

I was trying to integrate vault-lambda-extension in my lambda function. I followed all the steps mentioned in the blog: 
https://learn.hashicorp.com/tutorials/vault/aws-lambda?in=vault/app-integration
and created all setups by following the terraform. But while executing the go function I am getting this error:

"errorMessage": "error reading file: open /tmp/vault_secret.json: no such file or directory",
  "errorType": "wrapError"

**Comment by tomhjp** [comment]
Hi @rudub, because of the different lifetime that extensions work on from functions, sometimes not all of the logs from the extension are returned in the function invocation logs. Please could you check the log group in CloudWatch, and paste the full logs here? Please could you also include the environment variables you have configured?

**Comment by rudub** [comment]
This is the error log:

Executing the above mentioned lambda but getting below error:
START RequestId: 7c127d29-e028-4393-a29c-93e8de68439a Version: $LATEST
174b248c-08da-47f2-a2c0-457a813ad827[vault-lambda-extension] 2021/05/12 11:34:17 Initialising
[vault-lambda-extension] 2021/05/12 11:34:17 attemping Vault login...
EXTENSION	Name: vault-lambda-extension	State: Registered	Events: [INVOKE,SHUTDOWN]
END RequestId: 7c127d29-e028-4393-a29c-93e8de68439a
REPORT RequestId: 7c127d29-e028-4393-a29c-93e8de68439a	Duration: 5004.39 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 27 MB	
2021-05-12T11:34:21.120Z 7c127d29-e028-4393-a29c-93e8de68439a Task timed out after 5.00 seconds

environment variable are:
VAULT_ADDR
VAULT_AUTH_PROVIDER
VAULT_AUTH_ROLE
VAULT_SECRET_PATH

**Comment by tomhjp** [comment]
Are `error reading file: open /tmp/vault_secret.json: no such file or directory` and `Task timed out after 5.00 seconds` from the same run? I wouldn't think that's possible because for the latter it looks like you are hitting a timeout, and the extension never finishes initialising, so the function should never get a chance to start.

The only way I can think this might be possible is if you're hitting the same issue as #31. In which case it's important to note that static code in your function outside of the handler can't assume that files getting written by the extension are already there. Function initialisation and extension initialisation happen in parallel, so the only way to prevent a race is to read the file inside your function handler function.

As to why you are getting timeouts, it's hard to speculate in any detail, but I would suggest it's most likely to be that your Vault instance is not reachable from Lambda. I know the guide does not work in very old AWS accounts that don't default to putting everything in a private VPC, so you might want to check some of your security group rules and verify whether it's possible to connect to Vault from your function without the extension installed.

**Comment by rudub** [comment]
sorry, my bad, there are 2 lambda functions one which is provided in the vault-lambda blog with go language, which is having this error:

START RequestId: 7c5aefb6-971d-47f0-ba25-b9c92feba67c Version: $LATEST
[vault-lambda-extension-function] Received: 
[vault-lambda-extension-function] Reading file /tmp/vault_secret.json
error reading file: open /tmp/vault_secret.json: no such file or directory: wrapError
null
END RequestId: 7c5aefb6-971d-47f0-ba25-b9c92feba67c
REPORT RequestId: 7c5aefb6-971d-47f0-ba25-b9c92feba67c	Duration: 1.07 ms	Billed Duration: 2 ms	Memory Size: 128 MB	Max Memory Used: 33 MB	Init Duration: 85.87 ms	


the other one is python lambda which has the Timeout error.

**Comment by rudub** [comment]
I added vpc and SG in my lambda and now I am getting different error :

* error validating X-Vault-AWS-IAM-Server-ID header: missing header "X-Vault-AWS-IAM-Server-ID"
EXTENSION	Name: vault-lambda-extension	State: Registered	Events: [INVOKE,SHUTDOWN]
END RequestId: 8392a484-a86f-4930-9d49-ac25e316ec8c
REPORT RequestId: 8392a484-a86f-4930-9d49-ac25e316ec8c	Duration: 4644.12 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 35 MB	
RequestId: 8392a484-a86f-4930-9d49-ac25e316ec8c Error: exit status 1
Extension.Crash

**Comment by rudub** [comment]
The above solution modifying AWS client config solved the problem.
