### ISSUE TITLE
VAULT_ADDR collision

### ISSUE THREAD

**Issue by babbottscott** [hashicorp/vault-lambda-extension#40]
We have a function that expects to be provided the environment variable `VAULT_ADDR`. Since this extension also wants to use `VAULT_ADDR`, and I know of no way to provide two different `VAULT_ADDR` values to the extension and the function, this leaves us in a conundrum.

Suggestion: Add support in vault-lambda-extension for a new environment variable - `VLE_VAULT_ADDR`.  If set, this would take precedence over `$VAULT_ADDR`, allowing us to follow the recommended method for reading secrets by setting lambda env to:
```
VLE_VAULT_ADDR=https://myactualvault.example.com:8200
VAULT_ADDR=http://127.0.0.1:8200
```

**Comment by tomhjp** [comment]
Hi @babbottscott, thanks for opening this issue, it's always great to get feedback. I'm curious to learn more about your function because the use-case sounds surprising to me. Why does the function need a `VAULT_ADDR` different from the extension, is the function using `VAULT_ADDR` to talk to something that isn't HashiCorp Vault, or is it just a different Vault URL?

Without knowing more, I'm hesitant to add an alias for `VAULT_ADDR` because we're very well standardised on `VAULT_ADDR` everywhere for Vault, and we actually didn't even write the code for consuming that environment variable in this repo, it's directly from the `api` module's [`ReadEnvironment`](https://github.com/hashicorp/vault/blob/41fa51a4cd6618675a4a902061835b25bf097322/api/client.go#L258) function.

**Comment by madorb** [comment]
I'm on OP's team. We have our vault instance running at say, `https://vault.foo.com` which we need to inform the extension to talk to. 

We also have a custom Vault Client library, that _also_ reads the `VAULT_ADDR` environment variable and, in the case of running on a lambda w/ extension, we need the client to actually talk to `http://127.0.0.1:8200` 

As far as I know there is no mechanism to set different environment variables for extensions vs the lambda process itself, so we run into a naming conflict. 

One potential solution is for us to change our lib to prefer a namespaced environment variable (`FOO_VAULT_ADDR`) - but we figured that could be a more general issue that may be worth providing a fix for in the extension itself.

**Comment by babbottscott** [comment]
> Without knowing more, I'm hesitant to add an alias for `VAULT_ADDR` because we're very well standardised on `VAULT_ADDR` everywhere for Vault

Sure.  The problem here is that vault-lamba-extension is not the vault consumer -- it's a proxy.  So a vault-consuming app, that reasonably expects to use the very standard `VAULT_ADDR` variable to find vault, is running under the same environment as vault-lambda-extension, which needs a different `VAULT_ADDR` value.

**Comment by tomhjp** [comment]
Thanks for the extra context, I see where you're coming from now, and that seems perfectly reasonable. I'm going to get some extra feedback from the team on this, but I'm leaning towards exactly the solution you propose.

**Comment by tomhjp** [comment]
#41 is merged now, and we'll be publishing a new version of the extension shortly.
